export const ADD_RECIPES = "ADD_RECIPES";
export const SELECTED_RECIPE = "SELECTED_RECIPE";

export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CHANGE_TASK_STATUS = "CHANGE_TASK_STATUS";

export const SET_SEARCH = "SET_SEARCH";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_SEARCH_DIET = "SET_SEARCH_DIET";